kind: pipeline
name: default

steps:
- name: build
  image: python
  commands:
  - apt-get update && apt-get install -y -q pypy libgc-dev
  - pip install sphinx sphinx_rtd_theme
  - wget https://bitbucket.org/pypy/pypy/downloads/pypy2.7-v7.1.0-src.tar.bz2
  - tar jxf pypy2.7-v7.1.0-src.tar.bz2
  - export RPY=$(pwd)/pypy2.7-v7.1.0-src/rpython/bin/rpython
  - make -C code
  - make -C code/benchmarks
